"""
Activity Model - EduAutismo IA

Represents educational activities generated for students.
"""

from typing import TYPE_CHECKING, Any, Dict, List

from sqlalchemy import ForeignKey, Integer, String, Text, Enum as SQLEnum, Boolean
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.db.base import BaseModel
from backend.app.utils.constants import ActivityType, DifficultyLevel

if TYPE_CHECKING:
    from backend.app.models.student import Student
    from backend.app.models.assessment import Assessment
    from backend.app.models.user import User


class Activity(BaseModel):
    """
    Activity model representing personalized educational activities.
    
    Activities are generated by AI based on student profiles and can be
    assessed for effectiveness.
    """

    __tablename__ = "activities"

    # Basic Information
    title: Mapped[str] = mapped_column(String(500), nullable=False, index=True)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Activity Type and Difficulty
    activity_type: Mapped[ActivityType] = mapped_column(
        SQLEnum(ActivityType, name="activity_type"),
        nullable=False,
        index=True
    )
    
    difficulty: Mapped[DifficultyLevel] = mapped_column(
        SQLEnum(DifficultyLevel, name="difficulty_level"),
        nullable=False
    )
    
    # Duration
    duration_minutes: Mapped[int] = mapped_column(Integer, nullable=False)
    
    # Content
    objectives: Mapped[List[str]] = mapped_column(ARRAY(String), nullable=False)
    materials: Mapped[List[str]] = mapped_column(ARRAY(String), nullable=False)
    instructions: Mapped[List[str]] = mapped_column(ARRAY(String), nullable=False)
    
    # Adaptations and Supports
    adaptations: Mapped[List[str] | None] = mapped_column(ARRAY(String), nullable=True)
    visual_supports: Mapped[List[str] | None] = mapped_column(ARRAY(String), nullable=True)
    success_criteria: Mapped[List[str] | None] = mapped_column(ARRAY(String), nullable=True)
    
    # Theme/Topic
    theme: Mapped[str | None] = mapped_column(String(255), nullable=True)
    tags: Mapped[List[str] | None] = mapped_column(ARRAY(String), nullable=True, index=True)
    
    # Generation Metadata
    generated_by_ai: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    generation_metadata: Mapped[Dict[str, Any] | None] = mapped_column(
        JSONB, 
        nullable=True,
        comment="AI generation parameters and metadata"
    )
    
    # Resources
    resources_urls: Mapped[List[str] | None] = mapped_column(ARRAY(String), nullable=True)
    attachments: Mapped[List[str] | None] = mapped_column(ARRAY(String), nullable=True)
    
    # Status
    is_published: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    is_template: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    
    # Foreign Keys
    student_id: Mapped[UUID] = mapped_column(
        ForeignKey("students.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    created_by_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True
    )
    
    # Relationships
    student: Mapped["Student"] = relationship("Student", back_populates="activities", lazy="selectin")
    created_by: Mapped["User"] = relationship("User", lazy="selectin")
    assessments: Mapped[List["Assessment"]] = relationship(
        "Assessment",
        back_populates="activity",
        cascade="all, delete-orphan",
        lazy="selectin"
    )

    def __repr__(self) -> str:
        """String representation."""
        return f"<Activity(id={self.id}, title={self.title}, type={self.activity_type})>"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for AI processing."""
        return {
            "title": self.title,
            "description": self.description,
            "type": self.activity_type.value,
            "difficulty": self.difficulty.value,
            "duration_minutes": self.duration_minutes,
            "objectives": self.objectives,
            "materials": self.materials,
            "instructions": self.instructions,
            "theme": self.theme,
        }
