"""initial migration with multiprofessional system

Revision ID: 0a32abc79858
Revises:
Create Date: 2025-11-21 19:54:55.491099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import custom types
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent.parent))
from app.db.types import GUID, PortableJSON, StringArray


# revision identifiers, used by Alembic.
revision: str = "0a32abc79858"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professionals",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "TEACHER",
                "SPECIAL_EDUCATOR",
                "SCHOOL_COORDINATOR",
                "SCHOOL_MANAGER",
                "PSYCHOPEDAGOGIST",
                "PSYCHOLOGIST",
                "PSYCHIATRIST",
                "NEUROPEDIATRICIAN",
                "OCCUPATIONAL_THERAPIST",
                "SPEECH_THERAPIST",
                "PHYSIOTHERAPIST",
                "SOCIAL_WORKER",
                "NUTRITIONIST",
                name="professional_role",
            ),
            nullable=False,
        ),
        sa.Column("specialization", sa.String(length=255), nullable=True),
        sa.Column("license_number", sa.String(length=100), nullable=True),
        sa.Column("organization", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_professionals_email"), "professionals", ["email"], unique=True)
    op.create_index(
        op.f("ix_professionals_is_active"), "professionals", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_professionals_name"), "professionals", ["name"], unique=False)
    op.create_index(op.f("ix_professionals_role"), "professionals", ["role"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "TEACHER", "PARENT", "THERAPIST", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("bio", sa.String(length=1000), nullable=True),
        sa.Column("institution", sa.String(length=255), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("reset_token", sa.String(length=255), nullable=True),
        sa.Column("reset_token_expires", sa.DateTime(), nullable=True),
        sa.Column("verification_token", sa.String(length=255), nullable=True),
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "students",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("diagnosis", sa.String(length=500), nullable=False),
        sa.Column(
            "tea_level", sa.Enum("LEVEL_1", "LEVEL_2", "LEVEL_3", name="tea_level"), nullable=True
        ),
        sa.Column("interests", StringArray(), nullable=False),
        sa.Column("learning_profile", PortableJSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("teacher_id", GUID(length=36), nullable=False),
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_students_name"), "students", ["name"], unique=False)
    op.create_index(op.f("ix_students_teacher_id"), "students", ["teacher_id"], unique=False)
    op.create_table(
        "activities",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "COGNITIVE",
                "SOCIAL",
                "MOTOR",
                "SENSORY",
                "COMMUNICATION",
                "DAILY_LIVING",
                "ACADEMIC",
                name="activity_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum("VERY_EASY", "EASY", "MEDIUM", "HARD", "VERY_HARD", name="difficulty_level"),
            nullable=False,
        ),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("objectives", StringArray(), nullable=False),
        sa.Column("materials", StringArray(), nullable=False),
        sa.Column("instructions", StringArray(), nullable=False),
        sa.Column("adaptations", StringArray(), nullable=True),
        sa.Column("visual_supports", StringArray(), nullable=True),
        sa.Column("success_criteria", StringArray(), nullable=True),
        sa.Column("theme", sa.String(length=255), nullable=True),
        sa.Column("tags", StringArray(), nullable=True),
        sa.Column("generated_by_ai", sa.Boolean(), nullable=False),
        sa.Column(
            "generation_metadata",
            PortableJSON(),
            nullable=True,
            comment="AI generation parameters and metadata",
        ),
        sa.Column("resources_urls", StringArray(), nullable=True),
        sa.Column("attachments", StringArray(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("student_id", GUID(length=36), nullable=False),
        sa.Column("created_by_id", GUID(length=36), nullable=True),
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activities_activity_type"), "activities", ["activity_type"], unique=False
    )
    op.create_index(
        op.f("ix_activities_created_by_id"), "activities", ["created_by_id"], unique=False
    )
    op.create_index(op.f("ix_activities_student_id"), "activities", ["student_id"], unique=False)
    op.create_index(op.f("ix_activities_tags"), "activities", ["tags"], unique=False)
    op.create_index(op.f("ix_activities_title"), "activities", ["title"], unique=False)
    op.create_table(
        "intervention_plans",
        sa.Column("student_id", GUID(length=36), nullable=False),
        sa.Column("created_by_id", GUID(length=36), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("strategies", PortableJSON(), nullable=False),
        sa.Column("target_behaviors", PortableJSON(), nullable=False),
        sa.Column("success_criteria", PortableJSON(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "review_frequency",
            sa.Enum("DAILY", "WEEKLY", "BIWEEKLY", "MONTHLY", "QUARTERLY", name="review_frequency"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "PAUSED", "COMPLETED", "CANCELLED", name="plan_status"),
            nullable=False,
        ),
        sa.Column("progress_percentage", sa.Integer(), nullable=False),
        sa.Column("progress_notes", PortableJSON(), nullable=True),
        sa.Column("required_materials", PortableJSON(), nullable=True),
        sa.Column("resources", PortableJSON(), nullable=True),
        sa.Column("last_reviewed_at", sa.Date(), nullable=True),
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["professionals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_intervention_plans_end_date"), "intervention_plans", ["end_date"], unique=False
    )
    op.create_index(
        op.f("ix_intervention_plans_start_date"), "intervention_plans", ["start_date"], unique=False
    )
    op.create_index(
        op.f("ix_intervention_plans_status"), "intervention_plans", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_intervention_plans_student_id"), "intervention_plans", ["student_id"], unique=False
    )
    op.create_table(
        "professional_observations",
        sa.Column("student_id", GUID(length=36), nullable=False),
        sa.Column("professional_id", GUID(length=36), nullable=False),
        sa.Column(
            "observation_type",
            sa.Enum(
                "BEHAVIORAL",
                "ACADEMIC",
                "SOCIAL",
                "EMOTIONAL",
                "SENSORY",
                "COMMUNICATION",
                "MOTOR",
                "CLINICAL",
                "GENERAL",
                name="observation_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "context",
            sa.Enum(
                "CLASSROOM",
                "RECESS",
                "PE_CLASS",
                "THERAPY",
                "LUNCH",
                "TRANSITION",
                "GROUP_ACTIVITY",
                "INDIVIDUAL_ACTIVITY",
                "HOME",
                "OTHER",
                name="observation_context",
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("behavioral_indicators", PortableJSON(), nullable=True),
        sa.Column("socioemotional_indicators", PortableJSON(), nullable=True),
        sa.Column("severity_level", sa.Integer(), nullable=False),
        sa.Column("requires_intervention", sa.Boolean(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("tags", PortableJSON(), nullable=True),
        sa.Column("attachments", PortableJSON(), nullable=True),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["professional_id"], ["professionals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_professional_observations_observation_type"),
        "professional_observations",
        ["observation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_observations_professional_id"),
        "professional_observations",
        ["professional_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_observations_student_id"),
        "professional_observations",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "socioemotional_indicators",
        sa.Column("student_id", GUID(length=36), nullable=False),
        sa.Column("professional_id", GUID(length=36), nullable=False),
        sa.Column(
            "indicator_type",
            sa.Enum(
                "EMOTIONAL_REGULATION",
                "SOCIAL_INTERACTION",
                "COMMUNICATION_SKILLS",
                "ADAPTIVE_BEHAVIOR",
                "SENSORY_PROCESSING",
                "ATTENTION_FOCUS",
                "ANXIETY_LEVEL",
                "FRUSTRATION_TOLERANCE",
                "SELF_REGULATION",
                "PEER_RELATIONSHIP",
                "EXECUTIVE_FUNCTION",
                "FLEXIBILITY",
                name="indicator_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "context",
            sa.Enum(
                "CLASSROOM",
                "RECESS",
                "THERAPY_SESSION",
                "GROUP_ACTIVITY",
                "INDIVIDUAL_ACTIVITY",
                "TRANSITION",
                "STRUCTURED_TASK",
                "UNSTRUCTURED_TIME",
                "HOME",
                "OTHER",
                name="measurement_context",
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("observations", sa.Text(), nullable=True),
        sa.Column("specific_behaviors", sa.Text(), nullable=True),
        sa.Column("environmental_factors", sa.Text(), nullable=True),
        sa.Column("triggers", sa.Text(), nullable=True),
        sa.Column("supports_used", sa.Text(), nullable=True),
        sa.Column("measured_at", sa.DateTime(), nullable=False),
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["professional_id"], ["professionals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_socioemotional_indicators_indicator_type"),
        "socioemotional_indicators",
        ["indicator_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_socioemotional_indicators_measured_at"),
        "socioemotional_indicators",
        ["measured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_socioemotional_indicators_professional_id"),
        "socioemotional_indicators",
        ["professional_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_socioemotional_indicators_student_id"),
        "socioemotional_indicators",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "assessments",
        sa.Column(
            "completion_status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                "ABANDONED",
                "NEEDS_ASSISTANCE",
                name="completion_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "engagement_level",
            sa.Enum("NONE", "LOW", "MEDIUM", "HIGH", "VERY_HIGH", name="engagement_level"),
            nullable=False,
        ),
        sa.Column(
            "difficulty_rating",
            sa.Enum(
                "TOO_EASY",
                "SLIGHTLY_EASY",
                "APPROPRIATE",
                "SLIGHTLY_HARD",
                "TOO_HARD",
                name="difficulty_rating",
            ),
            nullable=False,
        ),
        sa.Column(
            "actual_duration_minutes",
            sa.Integer(),
            nullable=True,
            comment="Actual time taken vs planned duration",
        ),
        sa.Column("notes", sa.Text(), nullable=True, comment="Teacher's observations and notes"),
        sa.Column(
            "strengths_observed", sa.Text(), nullable=True, comment="What the student did well"
        ),
        sa.Column(
            "challenges_observed", sa.Text(), nullable=True, comment="Difficulties encountered"
        ),
        sa.Column(
            "recommendations", sa.Text(), nullable=True, comment="Suggestions for future activities"
        ),
        sa.Column(
            "skills_demonstrated",
            PortableJSON(),
            nullable=True,
            comment="Skills checklist or rubric results",
        ),
        sa.Column(
            "behavioral_notes",
            PortableJSON(),
            nullable=True,
            comment="Behavioral observations (focus, cooperation, etc.)",
        ),
        sa.Column(
            "independence_level",
            sa.String(length=50),
            nullable=True,
            comment="Level of independence (full, partial, minimal, dependent)",
        ),
        sa.Column(
            "assistance_needed",
            sa.String(length=255),
            nullable=True,
            comment="Type of assistance provided",
        ),
        sa.Column(
            "modifications_made",
            sa.Text(),
            nullable=True,
            comment="Any on-the-fly modifications to the activity",
        ),
        sa.Column(
            "objectives_met",
            PortableJSON(),
            nullable=True,
            comment="Which objectives were achieved",
        ),
        sa.Column("activity_id", GUID(length=36), nullable=False),
        sa.Column("student_id", GUID(length=36), nullable=False),
        sa.Column("assessed_by_id", GUID(length=36), nullable=True),
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["assessed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessments_activity_id"), "assessments", ["activity_id"], unique=False
    )
    op.create_index(
        op.f("ix_assessments_assessed_by_id"), "assessments", ["assessed_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_assessments_completion_status"), "assessments", ["completion_status"], unique=False
    )
    op.create_index(op.f("ix_assessments_student_id"), "assessments", ["student_id"], unique=False)
    op.create_table(
        "intervention_plan_professionals",
        sa.Column("intervention_plan_id", GUID(length=36), nullable=True),
        sa.Column("professional_id", GUID(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["intervention_plan_id"], ["intervention_plans.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["professional_id"], ["professionals.id"], ondelete="CASCADE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("intervention_plan_professionals")
    op.drop_index(op.f("ix_assessments_student_id"), table_name="assessments")
    op.drop_index(op.f("ix_assessments_completion_status"), table_name="assessments")
    op.drop_index(op.f("ix_assessments_assessed_by_id"), table_name="assessments")
    op.drop_index(op.f("ix_assessments_activity_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(
        op.f("ix_socioemotional_indicators_student_id"), table_name="socioemotional_indicators"
    )
    op.drop_index(
        op.f("ix_socioemotional_indicators_professional_id"), table_name="socioemotional_indicators"
    )
    op.drop_index(
        op.f("ix_socioemotional_indicators_measured_at"), table_name="socioemotional_indicators"
    )
    op.drop_index(
        op.f("ix_socioemotional_indicators_indicator_type"), table_name="socioemotional_indicators"
    )
    op.drop_table("socioemotional_indicators")
    op.drop_index(
        op.f("ix_professional_observations_student_id"), table_name="professional_observations"
    )
    op.drop_index(
        op.f("ix_professional_observations_professional_id"), table_name="professional_observations"
    )
    op.drop_index(
        op.f("ix_professional_observations_observation_type"),
        table_name="professional_observations",
    )
    op.drop_table("professional_observations")
    op.drop_index(op.f("ix_intervention_plans_student_id"), table_name="intervention_plans")
    op.drop_index(op.f("ix_intervention_plans_status"), table_name="intervention_plans")
    op.drop_index(op.f("ix_intervention_plans_start_date"), table_name="intervention_plans")
    op.drop_index(op.f("ix_intervention_plans_end_date"), table_name="intervention_plans")
    op.drop_table("intervention_plans")
    op.drop_index(op.f("ix_activities_title"), table_name="activities")
    op.drop_index(op.f("ix_activities_tags"), table_name="activities")
    op.drop_index(op.f("ix_activities_student_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_created_by_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_activity_type"), table_name="activities")
    op.drop_table("activities")
    op.drop_index(op.f("ix_students_teacher_id"), table_name="students")
    op.drop_index(op.f("ix_students_name"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_professionals_role"), table_name="professionals")
    op.drop_index(op.f("ix_professionals_name"), table_name="professionals")
    op.drop_index(op.f("ix_professionals_is_active"), table_name="professionals")
    op.drop_index(op.f("ix_professionals_email"), table_name="professionals")
    op.drop_table("professionals")
    # ### end Alembic commands ###
